#https://www.cnblogs.com/babycomeon/p/11161073.html
server: 
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          #是否与服务注册于发现组件进行结合，通过 serviceId 转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据serviceId 创建路由的功能。
          #将gateway注册到服务中心之后，网关会自动代理所有的在注册中心的服务，访问这些服务的语法为：http://网关地址：端口/服务中心注册serviceId/具体的url,
          #注意服务中心注册serviceId显示的名称是大写的，路径访问时必须是大写的
          enabled: true 
      routes:
        #上面这段配置的意思是，配置了一个 id 为 my-first-gateway-route 的路由规则，当访问地址 http://localhost:8080/gateway-route-test时会自动转发到地址：https://www.baidu.com
        - id: gateway-shop-webchat # 我们自定义的路由 ID，保持唯一
          uri: lb://shop-webchat #目标服务地址
          predicates: #路由条件，Predicate 接受一个输入参数，返回一个布尔值结果。该接口包含多种默认方法来将 Predicate 组合成其他复杂的逻辑（比如：与，或，非）。
            - Path=/auth/**
          filters:
          - StripPrefix=1
        - id: gateway-shop-member
          uri: lb://shop-member
          predicates:
            - Path=*/member/**
          filters:
          - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/

logging:
  level:
    org.springframework.cloud.gateway: debug