server: 
  port: 80
spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka/

zuul:
  routes:
    route-api-shop-member: 
      path: /api-shop-member/**
      service-id: shop-member
    route-api-shop-webchat:
      path: /api-shop-webchat/**
      service-id: shop-webchat 
    